pet_project/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from Tracker.views import *
from Tracker.apiviews import IndexAPIView, ProjectAPIView, TaskDetailAPIView, ProjectDetailAPIView
from accounts.views import user_login, \
    user_logout, \
    UserRegisterView, \
    UserDetailView, \
    UsersListView, \
    UserChangeView, \
    ChangePasswordView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='home'),
    path('task_info/<int:pk>/', TaskDetailView.as_view(), name='task_info'),
    path('task_del/<int:pk>/', TaskDeleteView.as_view(), name='task_delete'),
    path('task_add', TaskAddView.as_view(), name='task_add'),
    path('task_edit/<int:pk>/', TaskEditView.as_view(), name='task_edit'),
    path('project/', ProjectView.as_view(), name='project'),
    path('project_info/<int:pk>/', ProjectDetailView.as_view(), name='project_info'),
    path('project_add/', ProjectAddView.as_view(), name='project_add'),

    path('users/login/', user_login, name='login'),
    path('user_detail/<int:pk>/', UserDetailView.as_view(), name='user_detail'),
    path('users_all', UsersListView.as_view(), name='users_all'),
    path('add_user/project/<int:pk>/', AddUserProject.as_view(), name='add_user'),
    path('user/<int:pk>/edit', UserChangeView.as_view(), name='edit_profile'),
    path('user/<int:pk>/change_password', ChangePasswordView.as_view(), name='change_password'),

    path('logout/', user_logout, name='logout'),
    path('registration/', UserRegisterView.as_view(), name='registration'),

    path('api/v1/home/', IndexAPIView.as_view()),
    path('api/v1/projects/', ProjectAPIView.as_view()),
    path('api/v1/task_info/<int:pk>/', TaskDetailAPIView.as_view()),
    path('api/v1/project_info/<int:pk>/', ProjectDetailAPIView.as_view()),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Tracker/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth import get_user_model

class Type(models.Model):
    name = models.TextField(max_length=100, null=False, blank=False, verbose_name='Тип задачи')

    def __str__(self):
        return self.name

class Status(models.Model):
    name = models.TextField(max_length=100, null=False, blank=False, verbose_name='Статус задачи')

    def __str__(self):
        return self.name

class Project(models.Model):
    date_start = models.DateField(verbose_name='Дата начала', null=False, blank=False)
    date_end = models.DateField(verbose_name='Дата окончания', blank=True, null=True)
    project_name = models.CharField(max_length=250, null=False, blank=False, verbose_name='Наименование проекта')
    project_description = models.TextField(max_length=1000, null=True, verbose_name='Описание проекта')
    users = models.ManyToManyField(User, related_name='users', blank=True, verbose_name='Пользователи')
    author = models.ForeignKey(get_user_model(), on_delete=models.SET_DEFAULT, default=1, verbose_name='Автор')

    def __str__(self):
        return self.project_name

    class Meta:
        permissions = [
            ('can_add_user_to_project', 'Can add user to project')
        ]

class Task(models.Model):
    summary = models.CharField(max_length=250, null=False, blank=False, verbose_name='Заголовок')
    description = models.TextField(max_length=1000, null=True, verbose_name='Описание')
    status = models.ForeignKey(Status, related_name='Tasks', on_delete=models.PROTECT, verbose_name='Статус')
    type = models.ManyToManyField(Type, related_name='type', blank=True, verbose_name='Тип задачи')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Время создания')
    update_at = models.DateTimeField(auto_now=True, verbose_name='Время изменения')
    project = models.ForeignKey(Project, related_name='tasks', default=None, on_delete=models.CASCADE, verbose_name='Проект')

    def __str__(self):
        return self.summary

templates/Project/add_user_project.html
<title>Добавление пользователя</title>
{% extends 'base.html' %}
{% block content %}

<div class="users_add" style="color: lightcyan">
<form action="{% url 'add_user' project.id%}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary btn-sm">Сохранить</button>
</form>
</div>
{% endblock %}

templates/Project/project_add.html
<title>Создать проект</title>
{% extends 'base.html' %}
{% block content %}

<div class="task_add" style="color: lightcyan">
<form action="{% url 'project_add' %} " method="post">
    {% csrf_token %}
    {{ form.non_field_errors }}

    <label for="{{ form.date_start.id_for_label }}" class="form-label">Дата начала: </label>
        {{ form.date_start }}

        <div class="invalid-feedback" style="display: block; font-size: medium" >
          {{ form.date_start.errors }}
        </div>
        <br>

    <label for="{{ form.date_end.id_for_label }}" class="form-label">Дата окончания: </label>
        {{ form.date_end }}
        <div class="invalid-feedback" style="display: block; font-size: medium">
            {{ form.date_end.errors }}
        </div>
        <br>

    <label for="{{ form.project_name.id_for_label }}" class="form-label"><h3>Наименование проекта:</h3> </label>
        <br>
        {{ form.project_name }}
        <div class="invalid-feedback">
            {{ form.project_name.errors }}
        </div>
        <br>

    <label for="{{ form.project_description.id_for_label }}" class="form-label"><h4>Описание:</h4></label>
        <br>
        {{ form.project_description }}
        <div class="invalid-feedback">
            {{ form.project_description.errors }}
        </div>
    <br>
<br>
    <button type="submit" class="btn btn-primary btn-sm">Добавить</button>

</form>
</div>
{% endblock %}

templates/Project/project_info.html
<title>Описание проекта</title>
{% extends 'base.html' %}
{% block content %}
<div class="info">
<div class="card w-50">
  <div class="card-body">
    <h4 class="card-title">{{ project.project_name }}</h4>
      <h5 class="card-title">Описание: {{ project.project_description }}</h5>
        <p>Участники проекта:</p>
          {% for i in project.users.all %}
              {{ i }}{% if not forloop.last %},{% endif %}
          {% empty %}
            <p><i>Сейчас нет участников</i></p>
              {% endfor %}
        <br>
        {% if perms.Tracker.can_add_user_to_project %}
            <a href="{% url 'add_user' project.id%}"><button type="submit" class="btn btn-secondary">Добавить/Удалить участника</button></a></li>
        {% endif %}
      <br>
        <p>Задачи проекта:</p>
        {% for task in project.tasks.all %}
             <b> {{ task }} </b>
            <div class="list-group">
            <ul class="list">
                <li><a href="{% url 'task_info' task.id%}"><button type="submit" class="btn btn-success">Подробно</button></a></li>
                <br>
                {% if perms.Tracker.change_task or project.author == request.user %}
                <li><a href="{% url 'task_edit' task.id %}"><button type="submit" class="btn btn-success">Изменить</button></a></li>
                {% endif %}
                <br>
                {% if perms.Tracker.delete_task or project.author == request.user%}
                <li>
                    <form action="{% url 'task_delete' task.id%}" style="display: inline" method="post">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-danger">Удалить</button>
                    </form>
                    {% endif %}
                    <hr>
                </li>
            </ul>
            </div>
            {% empty %}
            <p><i>на текущий момент у проекта нет связанных задач</i></p>
    </div>
        {% endfor %}
  </div>
</div>
</div>
{% endblock %}

templates/Project/projects.html
<title>Мои проекты</title>
{% extends 'base.html' %}
{% block content %}
{% if perms.Tracker.add_project %}
<a href="{% url 'project_add' %}"><i class="fas fa-plus fa-4x"></i></a>
{% endif %}
{% for i in project %}
<div class="content">
<div class="row">
    <div class="card" style="width: 25rem;">
      <div class="card-body">
        <h4 class="card-title">{{ i.project_name }}</h4>
        <a href="{% url 'project_info' i.id%}" class="btn btn-primary">Подробно</a>
      </div>
    </div>
</div>
</div>
<br>
{% endfor %}
{% endblock %}